import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Footer from "@/containers/public/footer";
import { Toaster } from "sonner";
import "./globals.css";
const kanit = Kanit({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html
        lang="en"
        className={`${kanit.variable} h-full antialiased`}
        >
            <body className={`${kanit.className} min-h-full flex flex-col h-screen w-screen overflow-hidden `}>
                <div className=" w-full h-full overflow-auto overscroll-none bg-palette1/40">
                    {children}
                    <Footer/>
                </div>
                <Toaster richColors closeButton position="top-center"/>
            </body>
        </html>
    );
}
